### PR TITLE
Add GUNIV3DAIUSDC2-A

### PR DESCRIPTION
**Pull request by brianmcmichael**

### CODE REVIEW

**Comment by brianmcmichael** [comment]
Also paging @NiklasKunkel and @madumas

**Review by dizzy — COMMENTED** [review]
since BAT-A was fully offboarded IMO worth removing it altogether

**Review by naszam — APPROVED** [review]
Checked:

- `guniv3daiusdc2` OSM Address Matches Spell Code and Changelog 1.9.12 `PIP_GUNIV3DAIUSDC2`
- `guniv3daiusdc2` Added in the daily pokes block
- `guniv3daiusdc2` OSM `poke` Looks Good
- `guniv3daiusdc2` Spot `poke` Looks Good
- `guniv3daiusdc2` Tests Looks Good
- Test PASS

Note: consider offboarding updates upon Oracle CU request.

LGTM

**Review by dizzy — APPROVED** [review]

**Review by naszam — APPROVED** [review]
LGTMerge

**Pull request merged**
